// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYCNtXLV9y1QlmUTm9KRR30ORaT47iF38',
    appId: '1:834686690752:web:56ae7fee37cb5accc39425',
    messagingSenderId: '834686690752',
    projectId: 'authentication-system-ap-51e2b',
    authDomain: 'authentication-system-ap-51e2b.firebaseapp.com',
    storageBucket: 'authentication-system-ap-51e2b.appspot.com',
    measurementId: 'G-QPC3CHGPCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhgmJZP_FeStP2HfMf7M3cTkXD8S_XYgM',
    appId: '1:834686690752:android:11dccf63e2f214bfc39425',
    messagingSenderId: '834686690752',
    projectId: 'authentication-system-ap-51e2b',
    storageBucket: 'authentication-system-ap-51e2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCtGCvrikSiZVA3M2t3LJxNjI-xd9j4gY',
    appId: '1:834686690752:ios:9e5b7da0ec359ff5c39425',
    messagingSenderId: '834686690752',
    projectId: 'authentication-system-ap-51e2b',
    storageBucket: 'authentication-system-ap-51e2b.appspot.com',
    iosClientId: '834686690752-a8v04bd5o2v1n7v0kk2c3j8jrg7dvudi.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationSystem',
  );
}
